name: Ubuntu Linux (x86_64)

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build & Test Rust Crate
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev mesa-common-dev libsdl2-dev libglm-dev llvm-dev

      - name: Update Local Toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Run Tests
        run: |
          cargo check
          cargo test --all

      - name: Build Debug
        run: cargo build
